/*
 * draw.h
 *
 * Created: 7-2-2013 15:13:33
 *  Author: Koen Beckers
 */ 


#ifndef DRAW_H_
#define DRAW_H_

#define DATE_X					3
#define DATE_Y					0

#define TIME_X					DISPLAY_SCREEN_WIDTH - 33
#define TIME_Y					0

#define BUTTON_DOWN_X			(DISPLAY_SCREEN_WIDTH/2)
#define BUTTON_DOWN_Y			SET_Y + UBUNTU_BOLD_14_HEIGHT + 2
#define BUTTON_DOWN_WIDTH		12
#define BUTTON_DOWN_HEIGHT		8

#define BUTTON_UP_X				BUTTON_DOWN_X + BUTTON_DOWN_WIDTH + 4
#define BUTTON_UP_Y				BUTTON_DOWN_Y
#define BUTTON_UP_WIDTH			12
#define BUTTON_UP_HEIGHT		8

#define BUTTON_PRES_X			BUTTON_UP_X + BUTTON_UP_WIDTH + 4
#define BUTTON_PRES_Y			BUTTON_UP_Y
#define BUTTON_PRES_WIDTH		12
#define BUTTON_PRES_HEIGHT		8

#define BUTTON_AWAY_X			BUTTON_PRES_X + BUTTON_PRES_WIDTH + 4
#define BUTTON_AWAY_Y			BUTTON_PRES_Y
#define BUTTON_AWAY_WIDTH		12
#define BUTTON_AWAY_HEIGHT		8

#define PRESET_X				BUTTON_PRES_X + 2
#define PRESET_Y				BUTTON_PRES_Y - 15

#define INTERN_X				12
#define INTERN_Y				15
#define HOUSE_IN_X				2
#define HOUSE_IN_Y				INTERN_Y + 9


#define EXTERN_FONT				SMALLVALUEFONT
#define EXTERN_X				12
#define EXTERN_Y				44
#define HOUSE_EX_X				2
#define HOUSE_EX_Y				EXTERN_Y + 3

#define SET_X					(DISPLAY_SCREEN_WIDTH/2 + 2)
#define SET_Y					20

#define FLAME_X					DISPLAY_SCREEN_WIDTH - 8
#define FLAME_Y					DISPLAY_SCREEN_HEIGHT - 11

#define TOPBAR_Y				8

#define BATTERY_X				0
#define BATTERY_Y				TOPBAR_Y + 1

#define AWAYSCREEN_X				4
#define AWAYSCREEN_Y				7
#define AWAYSCREEN_WIDTH			119
#define AWAYSCREEN_HEIGHT			49
#define AWAYSCREEN_FIELDS_Y			24
#define AWAYSCREEN_FIELDS_HEIGHT	15
#define AWAYSCREEN_TOPBUTTONS_Y		11
#define AWAYSCREEN_BOTBUTTONS_Y		42
#define AWAYSCREEN_BUTTONS_WIDTH	19
#define AWAYSCREEN_BUTTONS_HEIGHT	10
#define AWAYSCREEN_OKCANCEL_WIDTH	15
#define AWAYSCREEN_OKCANCEL_X		9
#define AWAYSCREEN_X_DIFF			5


#endif /* DRAW_H_ */