/*
 * draw.h
 *
 * Created: 7-2-2013 15:13:33
 *  Author: Koen Beckers
 */ 


#ifndef DRAW_H_
#define DRAW_H_

#define DATE_X					3
#define DATE_Y					0

#define TIME_X					DISPLAY_SCREEN_WIDTH - 33
#define TIME_Y					0

#define BUTTON_DOWN_X			(DISPLAY_SCREEN_WIDTH/2)
#define BUTTON_DOWN_Y			SET_Y + UBUNTU_BOLD_14_HEIGHT + 2
#define BUTTON_DOWN_WIDTH		12
#define BUTTON_DOWN_HEIGHT		8

#define BUTTON_UP_X				BUTTON_DOWN_X + BUTTON_DOWN_WIDTH + 4
#define BUTTON_UP_Y				BUTTON_DOWN_Y
#define BUTTON_UP_WIDTH			12
#define BUTTON_UP_HEIGHT		8

#define BUTTON_PRES_X			BUTTON_UP_X + BUTTON_UP_WIDTH + 4
#define BUTTON_PRES_Y			BUTTON_UP_Y
#define BUTTON_PRES_WIDTH		12
#define BUTTON_PRES_HEIGHT		8

#define BUTTON_AWAY_X			BUTTON_PRES_X + BUTTON_PRES_WIDTH + 4
#define BUTTON_AWAY_Y			BUTTON_PRES_Y
#define BUTTON_AWAY_WIDTH		12
#define BUTTON_AWAY_HEIGHT		8

#define PRESET_X				BUTTON_PRES_X + 2
#define PRESET_Y				BUTTON_PRES_Y - 15

#define CURRENT_X				3
#define CURRENT_Y				20
#define SET_X					(DISPLAY_SCREEN_WIDTH/2 + 2)
#define SET_Y					20

#define FLAME_X					DISPLAY_SCREEN_WIDTH - 8
#define FLAME_Y					DISPLAY_SCREEN_HEIGHT - 11

#define TOPBAR_Y				8

#define BATTERY_X				0
#define BATTERY_Y				TOPBAR_Y + 1

#define AWAYSCREEN_X			DISPLAY_SCREEN_WIDTH / 8
#define AWAYSCREEN_Y			DISPLAY_SCREEN_HEIGHT / 8
#define AWAYSCREEN_WIDTH		DISPLAY_SCREEN_WIDTH - (2 * AWAYSCREEN_X)
#define AWAYSCREEN_HEIGHT		DISPLAY_SCREEN_HEIGHT - (2 * AWAYSCREEN_Y)
#define AWAYSCREEN_FIELDS_Y		((AWAYSCREEN_HEIGHT - (UBUNTU_BOLD_14_HEIGHT + 2)) / 2) + AWAYSCREEN_Y


#endif /* DRAW_H_ */